stages:
  - build

include:
  - project: 'BrainStone/MCPackPacker'
    ref: compiled/v1
    file: 'pack_packer.yml'

build:resourcepack:
  stage: build
  extends:
    - .pack_pack
  variables: 
    folder: resources
    output: UMultiTool.resources.zip

build:datapack:
  stage: build
  extends:
    - .pack_pack
  variables:
    folder: data
    output: UMultiTool.data.zip
