stages:
  - build

include:
  - project: 'BrainStone/MCPackPacker'
    ref: compiled/v1
    file: 'pack_packer.yml'

.auto_version:
  before_script:
    - VERSION="$(git --no-pager describe --tags --match 'v[0-9]*' --long | awk -F'-' '{ if (NF > 1) printf "%s.%s\n", $1, $2; else print $1 }')"
    - sed -i "s/DEV/$VERSION/" "$folder/pack.mcmeta"
    - cp CHANGELOG.md "$folder/"

build:resourcepack:
  stage: build
  extends:
    - .auto_version
    - .pack_pack
  variables: 
    folder: resources
    output: UMultiTool.resources.zip

build:datapack:
  stage: build
  extends:
    - .auto_version
    - .pack_pack
  variables:
    folder: data
    output: UMultiTool.data.zip
