stages:
  - build

include:
  - project: 'https://gitlab.project-creative.net/BrainStone/MCPackPacker'
    ref: compiled/v1
    file: 'pack_packer.yml'

create_resource_pack:
  stage: build
  extends:
    - .pack_pack
  variables: 
    folder: resources
    output: UMultiTool.resources.zip
